_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.0
            "6": 4.35.2
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
args:
    value: Namespace(save_path='./result/', config_path='./conf/config.yaml')
config:
    value:
        augment:
            flip: true
            remix:
                group_size: 4
                proba: 1
            scale:
                max: 1.25
                min: 0.25
                proba: 1
            shift_same: false
        batch_size: 4
        data:
            channels: 2
            metadata: ./metadata
            normalize: true
            samplerate: 44100
            segment: 11
            shift: 1
            sources:
                - drums
                - bass
                - other
                - vocals
            wav: /home/kaim/scratch/MUSDB18HQ_TEST
        ema:
            batch:
                - 0.9995
                - 0.9999
            epoch:
                - 0.9
                - 0.95
        epochs: 200
        misc:
            num_workers: 6
        model:
            audio_channels: 2
            band_SR:
                - 0.175
                - 0.392
                - 0.433
            band_kernel:
                - 3
                - 4
                - 16
            band_stride:
                - 1
                - 4
                - 16
            compress: 4
            conv_depths:
                - 3
                - 2
                - 1
            conv_kernel: 3
            dims:
                - 4
                - 32
                - 64
                - 128
            expand: 1
            hop_size: 1024
            nfft: 4096
            normalized: true
            num_dplayer: 6
            sources:
                - drums
                - bass
                - other
                - vocals
            win_size: 4096
        optim:
            beta2: 0.999
            decay_rate: 0.98
            decay_step: 10
            lr: 0.0005
            momentum: 0.9
            optim: adam
            weight_decay: 0
        save_every: null
        seed: 42
