_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 35
                - 49
                - 55
                - 71
            "2":
                - 1
                - 35
                - 49
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
args:
    value: Namespace(save_path='./result/', config_path='./conf/config.yaml')
config:
    value:
        augment:
            flip: true
            remix:
                group_size: 1
                proba: 1
            scale:
                max: 1.25
                min: 0.25
                proba: 1
            shift_same: false
        batch_size: 1
        data:
            channels: 2
            metadata: ./metadata
            normalize: true
            samplerate: 44100
            segment: 11
            shift: 0.5
            sources:
                - clean
                - hum
            wav: /home/kaim/projects/def-ichiro/kaim/data/guitar_hum_dataset_split
        ema:
            batch:
                - 0.9995
                - 0.9999
            epoch:
                - 0.9
                - 0.95
        epochs: 130
        misc:
            num_workers: 10
        model:
            audio_channels: 2
            band_SR:
                - 0.225
                - 0.372
                - 0.403
            band_kernel:
                - 3
                - 4
                - 16
            band_stride:
                - 1
                - 4
                - 16
            compress: 4
            conv_depths:
                - 3
                - 2
                - 1
            conv_kernel: 3
            dims:
                - 4
                - 64
                - 128
                - 256
            expand: 1
            hop_size: 1024
            nfft: 4096
            normalized: true
            num_dplayer: 6
            sources:
                - clean
                - hum
            win_size: 4096
        optim:
            beta2: 0.999
            decay_rate: 0.98
            decay_step: 10
            lr: 0.0003
            momentum: 0.9
            optim: adam
            weight_decay: 0
        save_every: null
        seed: 42
